set(HEADED_FILE "${BUILD_DIR}/version.h")
file(READ ${VERSION_FILE} ver)

string(REPLACE "." ";" VERSION_LIST ${ver})
list(GET VERSION_LIST 0 VERSION_MAJOR)
list(GET VERSION_LIST 1 VERSION_MINOR)
list(GET VERSION_LIST 2 VERSION_PATCH)
list(GET VERSION_LIST 3 VERSION_BUILD)
math(EXPR VERSION_BUILD "${VERSION_BUILD}+1")
file(WRITE ${VERSION_FILE} "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}.${VERSION_BUILD}")
file(WRITE ${HEADED_FILE} "
#define ${VERSION_NAME} \"${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}.${VERSION_BUILD}\"
#define ${VERSION_NAME}_MAJOR ${VERSION_MAJOR}
#define ${VERSION_NAME}_MINOR ${VERSION_MINOR}
#define ${VERSION_NAME}_PATCH ${VERSION_PATCH}")
	

if(MSVC)
configure_file(${RC_IN_FILE} ${BUILD_DIR}/version.rc @ONLY )
configure_file(${RC_H_IN_FILE} ${BUILD_DIR}/resource.h @ONLY )
set(CMAKE_VS_SDK_INCLUDE_DIRECTORIES ${CUSTOM_INCLUDE_DIRECTORIES})
endif(MSVC)

